version: '3'
services:
  mysql-db:
    container_name: mysql-db
    image: "mysql:8.0" 
    cap_add:
      - SYS_NICE
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: 1234s
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d/


        
  fake-news-detector-api:
    container_name: fake-news-detector-api
    image: alexxsnjr/fake-news-detector-api:latest
    restart: on-failure
    ports:
      - "8090:8090"
    depends_on: 
      - mysql-db  
    
    